apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: loadsqrx2639-tenant-component
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: loadsqrx2639-tenant-component
    app.kubernetes.io/part-of: loadsqrx2639-tenant-app
  name: loadsqrx2639-tenant-component
  namespace: loadsqrx2639-tenant
spec:
  path: /
  port:
    targetPort: 8081
  to:
    kind: Service
    name: loadsqrx2639-tenant-component
    weight: null
status: {}
